apiVersion: v1
kind: Service
metadata:
  name: echohostname
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: echohostname
  ports:
    - port: 80
      targetPort: 8000
