name: Build and Deploy to GKE

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "k8s/"
      - ".github/workflosw/gcp-deploy.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "k8s/"
      - ".github/workflosw/gcp-deploy.yml"
      
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: echohostname
        location: europe-west6-a

    - name: Deploy
      run: |-
        kubectl apply -k k8s/gcp
        kubectl rollout status deployment echohostname --timeout=600s
